### ISSUE TITLE
Q on initialization of A and B

### ISSUE THREAD

**Issue by RonanKMcGovern** [nikhil-ghosh-berkeley/loraplus#2]
Nice paper and looking forward to getting this in HuggingFace transformers and also Unsloth.

One Q - is there somehow a better way to initialize A and/or B to speed things up.

It would seem, intuitively, that initializing to some kind of an identity matrix or perhaps constructing with some of the top eigenvalues.

There is previous work showing that proper initialization can allow for removing skip connections and norms during training, and I just wonder if that can give speed up here (and/or potentially achieve some of the effects of differential training of A and B and/or some of the DoRA effects).

**Comment by nikhilgsh** [comment]
Hi Ronan thanks for the kind comments! Improving the initialization is something we have not really explored yet, but could definitely an interesting direction for future work!
