### ISSUE TITLE
No module name as loraplus

### ISSUE THREAD

**Issue by HelloWorldLTY** [nikhil-ghosh-berkeley/loraplus#5]
Hi, I try to use huggingface training method to apply loraplus to my own project. However, after checking the notebook, I did successfully import loraplus

```
import loraplus
```

did not work for me. I have installed the requirement packages in this project. Could you please help me? Thanks.

**Comment by nikhilgsh** [comment]
Sorry this was my mistake. In the notebook I did not update loraplus --> lora_plus since the import is being done from lora_plus.py. I've fixed the notebook. Let me know if it works now.

**Comment by HelloWorldLTY** [comment]
It works. Thanks a lot.

**Comment by HelloWorldLTY** [comment]
Hi, sorry to disturb you again. I tried to deploy your method in 3 H100 GPUs, but it seems that the estimated running time is extremely long:

<img width="763" alt="image" src="https://github.com/nikhil-ghosh-berkeley/loraplus/assets/43333475/4b087330-3c52-458e-9caf-71e3caf87122">

For a normal LoRA, I only need 3 hours. Does this method support H100? Thanks.

**Comment by nikhilgsh** [comment]
This is strange, the method should not incur any overhead compared to normal LoRA since we are only changing learning rates for different parameters.

**Comment by HelloWorldLTY** [comment]
Hi, I double check with it and I think the estimated time may not be accurate enough. I will keep on testing it under other datasets.
