### ISSUE TITLE
Many of the arguments in LoraPlusTrainingArguments seem to be unused

### ISSUE THREAD

**Issue by mst272** [nikhil-ghosh-berkeley/loraplus#6]
I don't see where some parameters in LoraPlusTrainingArguments are used, such as use_lora, etc. Can you explain where these parameters are used?

**Comment by nikhilgsh** [comment]
Sorry about this, the unused arguments like use_lora etc. were used for the training scripts in `glue`. LoraPlusTrainingArguments has now been updated to only have the special loraplus parameters.
